FROM python:3.12-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH to include the src directory
ENV PYTHONPATH=/usr/src/app/src

# copy src code
COPY ./src ./src

EXPOSE 4005

# start the server
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4005", "--proxy-headers"]
