name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_AUTH }}

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run flake8 for code linting
      run: |
        flake8 src/
    
    - name: Check code formatting with black
    run: |
      black --check src/
    
    - name: Format code with black
      run: |
        black src/
    
    - name: Run tests
      run: |
        pytest --cov=app --cov-report=xml src/tests/

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config=cloudbuild.yaml --project=${{ secrets.GCP_PROJECT_ID }} \
          --gcs-log-dir=gs://log_bucket-mlops-course-441515/cloud-build-logs
