name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_AUTH }}

    - name: Set GCP Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Submit Cloud Build
      run: gcloud builds submit --config=cloudbuild.yaml --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      run: gcloud run services replace service.yaml \
            --region us-central1 \
            --project ${{ secrets.GCP_PROJECT_ID }}
